name: Compile
on: [push]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ada-actions/toolchain@dev
        with:
          distrib: fsf
          target: native
      - run: sudo apt-get update
      - run: sudo apt-get -y install libfuse-dev libaunit*-dev
      - run: make
      - run: make test
        
